//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeLeavePortalAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ApplyLeave
    {
        public long Id { get; set; }
        public Nullable<int> AppliedBy { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> NoOfDays { get; set; }
        public string HalfDay { get; set; }
        public Nullable<System.DateTime> HalfDayDate { get; set; }
        public string Reason { get; set; }
        public string Approved { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public string UniqueId { get; set; }
        public string ApprovedBy { get; set; }
    }
}
